<?php echo $this->getContent() ?>
<div id="subheader">
    <div class="row">
        <div class="twelve columns">
            <p class="left">
                GIỚI THIỆU
            </p>
            <p class="right">

            </p>
        </div>
    </div>
</div>
<div class="hr">
</div>
<!-- CONTENT
================================================== -->
<div class="row">
    <div class="twelve columns">
        <h5><?php echo $data->title?></h5>
        <hr>
        <p>
            <?php echo $data->content?>
        </p>
    </div>
</div>

<div class="hr">
</div>