<?php echo $this->getContent() ?>
<div id="subheader">
    <div class="row">
        <div class="twelve columns">
            <p class="left">
                Đào tạo
            </p>
            <p class="right">
            </p>
        </div>
    </div>
</div>
<div class="hr">
</div>
<!-- CONTENT
================================================== -->
<div class="row">
    <!-- MAIN CONTENT-->
    <div class="eight columns">
        <div class="sectiontitle">
            <h4>Chưa có bài viết</h4>
        </div>
    </div><!-- end main content-->
    <!-- SIDEBAR-->
    <div class="four columns">
        <!-- Free Quote Form-->
        <h5>Danh mục đào tạo</h5>
        <a href="#" class="secondary button">ĐẠI HỌC</a>
        </br>
        <a href="#" class="secondary button">SAU ĐẠI HỌC</a>
    </div><!-- end sidebar-->
</div>
<div class="hr">
</div>
