<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Quản lý thông tin website</title>
    <?php $this->assets->outputCss() ?>
    <?php $this->assets->outputJs() ?>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <!-- Main Header -->
    <header class="main-header">
        <!-- Logo -->
        <a href="#" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>KHOA KTKT</b></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>KHOA KTKT</b></span>
        </a>
        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <!-- Navbar Right Menu -->
            <div class="navbar-custom-menu">
                <form action="/backend/users/logoff" method="post" id="logoutForm">
                    <input name="__RequestVerificationToken" type="hidden"
                           value=""/>
                    <ul class="nav navbar-nav">
                        <!-- Messages: style can be found in dropdown.less-->
                        <li class="dropdown messages-menu">

                        </li><!-- /.messages-menu -->
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="/backend/users/changepass" class="dropdown-toggle" title="Tài khoản">
                                <!-- The user image in the navbar-->
                                <img src="/img/backend/avatar5.png" class="user-image" alt="User Image">
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <span class="hidden-xs">admin</span>
                            </a>
                        </li>
                        <!-- Control Sidebar Toggle Button -->
                        <li>
                            <a href="javascript:document.getElementById('logoutForm').submit()"
                               data-toggle="control-sidebar"><i class="fa fa-power-off"></i></a>
                        </li>
                    </ul>
                </form>

            </div>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="/public/img/backend/avatar5.png" class="img-circle" alt="User Image">
                </div>
                <div class="pull-left info">
                    <p>admin</p>
                    <!-- Status -->
                    <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                </div>
            </div>
            <!-- Sidebar Menu -->
            <ul class="sidebar-menu">
                <li class="header">Danh Mục</li>
                <!-- Optionally, you can add icons to the links -->
                <li class="active"><a href="/backend/users/index"><i class="fa fa-product-hunt"></i> <span>Danh sách tài khoản</span></a></li>
                <li><a href="/backend/category/index"><i class="fa fa-credit-card"></i> <span>Danh mục tin tức & bài viết</span></a></li>
                <li><a href="/backend/picture/index"><i class="fa fa-user"></i> <span>Thư viện hình</span></a></li>
                <li><a href="/backend/news/index"><i class="fa fa-list-ol"></i> <span>Tin tức & Bài viết</span></a></li>
                <li><a href="/backend/sliderpic/index"><i class="fa fa-user"></i> <span>Khung hình trang chủ</span></a></li>
                <li><a href="/backend/contact/index"><i class="fa fa-user"></i> <span>Liên hệ</span></a></li>
                <li><a href="/backend/webconfig/index"><i class="fa fa-user"></i> <span>Cấu hình hệ thống</span></a></li>
            </ul><!-- /.sidebar-menu -->
        </section>
        <!-- /.sidebar -->
    </aside>
    <div class="content-wrapper">
        <?php echo $this->getContent(); ?>
    </div>
    <!-- Main Footer -->
    <footer class="main-footer">
        <!-- To the right -->
        <div class="pull-right hidden-xs">

        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; 2016 <a href="#">KHOA KẾ TOÁN KIỂM TOÁN</a></strong>
    </footer>
</div>
</body>
</html>
