<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<?php echo $this->getContent(); ?>
<?php
echo $this->tag->form(
    array(
        "/backend/category/save",
        "autocomplete" => "off",
        "class" => "form-horizontal",
        "name" => "editCat"
    )
);
?>
<section class="content-header">
    <h2>Sửa danh mục bài viết</h2>
</section>
<section class="content">
    <div class="arrage-popup">
        <div class="arrange-div form-group col-md-12">
            <label class="text-label col-md-2" for="Lang">Tên danh mục</label>
            <div class="col-md-6">
                <input class="form-control" id="name" name="name" type="text" value="<?php echo $data['cat']->name ?>"/>
                <input type="hidden" id="id" name="id" value="<?php echo $data['cat']->id ?>>"/>
            </div>
        </div>
        <div class="arrange-div form-group col-md-12">
            <label class="text-label col-md-2" for="pid">Danh mục cha</label>
            <div class="col-md-6">
                <select class="form-control" id="pid" name="pid">
                    <option value="0" <?php if ($data['cat']->pid == "0") echo "selected"; ?> >Chọn danh mục</option>
                    <?php foreach ($data['cats'] as $items): ?>
                        <?php if ($items->id == $data['cat']->pid)
                            echo "<option value=\"$items->id\" selected >$items->name</option>";
                        else
                            echo "<option value=\"$items->id\">$items->name</option>";
                        ?>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="arrange-div form-group col-md-12">
            <label class="text-label col-md-2" for="title">Title</label>
            <div class="col-md-6">
                <input class="form-control valid" id="title" maxlength="32" name="title" type="text" value="<?php echo $data['cat']->title ?>">
            </div>
        </div>
        <div class="arrange-div form-group col-md-12">
            <label class="text-label col-md-2" for="meta_description">Meta description</label>
            <div class="col-md-6">
                    <textarea class="form-control" cols="20" id="meta_description" maxlength="128" name="meta_description"
                              rows="2"><?php echo $data['cat']->meta_description ?></textarea>
            </div>
        </div>
        <div class="arrange-div form-group col-md-12">
            <label class="text-label col-md-2" for="Show">Mở/Đóng</label>
            <div class="col-md-6">
                <?php
                if ($data['cat']->is_status == '1')
                    echo $this->tag->checkField(array("is_status", "class" => "check-box", "value" => "1", "checked" => "checked"));
                else
                    echo $this->tag->checkField(array("is_status", "class" => "check-box", "value" => "0"));
                ?>
            </div>
        </div>
        <div class="arrange-div form-group col-md-12">
            <label class="text-label col-md-2" for="Price">Mô tả</label>
            <div class="col-md-6">
                <textarea class="form-control" cols="20" id="desc" maxlength="128" name="desc"
                          rows="2"><?php echo $data['cat']->desc ?></textarea>
            </div>
        </div>
        <div style="text-align:center" class="col-md-12">
            <input type="submit" value="Lưu" class="btn btn-info"/>
            <a href="/backend/category/index" class="btn btn-info">Về danh sách</a>
        </div>
        <div class="clearfix"></div>
    </div>
</section>
<?php echo $this->tag->endForm(); ?>
<script>
    $().ready(function () {
        // validate signup form on keyup and submit
        $("#editCat").validate({
            rules: {
                name: {
                    required: true,
                    minlength: 4
                }
            },
            messages: {
                name: {
                    required: "Nhập tên",
                    minlength: "Lớn hơn 4 ký tự"
                }
            }
        });
    });
</script>
